import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} bg-gradient-to-r from-indigo-400 to-cyan-400 text-white`}
      >
        <div className="w-full">
          <h1 className="m-4 text-xl font-bold">First Layout</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
